In [86]:
import numpy as np

# list, tuple, dictionary

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

In [87]:

my_array1

array([1, 2, 3, 4])

In [88]:
my_list2 = [11,22,33,44]

my_lists = [my_list1,my_list2]

In [89]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [90]:
#2-dimensional array
my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [91]:
#size of the array
my_array2.shape

(2L, 4L)

In [92]:
# Find out the data tyoe of the array
# http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html
my_array2.dtype

dtype('int32')

In [93]:
#special arrays

#Zeros
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [94]:
#Ones
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [95]:
np.ones(5).dtype

dtype('float64')

In [96]:
np.empty(5)


array([ 1.,  1.,  1.,  1.,  1.])

In [97]:

np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [98]:
#Identity array  (identity matirx)
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [99]:
# Using a range, python indexing starting from 0

np.arange(5)

array([0, 1, 2, 3, 4])

In [100]:
5/2

2.5

In [101]:
from __future__ import division

In [102]:
5/2


2.5

In [103]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [104]:
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [105]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [106]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [107]:
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])

In [108]:
# Python Basic Operators
#  % Modulus  //	Floor Division
5 % 2

1

In [109]:
9 // 4

2

In [110]:
# Python Assignment Operators

#  += Add AND, c += a is equivalent to c = c + a

a=5
a += 2
a


7

In [111]:
# -= Subtract AND, c -= a is equivalent to c = c - a
b=10
b -= 4
b

6

In [112]:
#   *= Multiply AND	c *= a is equivalent to c = c * a
#   /= Divide AND	c /= a is equivalent to c = c / a
#   %= Modulus AND	c %= a is equivalent to c = c % a
#  **= Exponent AND	c **= a is equivalent to c = c ** a
#  //= Floor Division	c //= a is equivalent to c = c // a

In [113]:
# Indexing 

In [114]:
arr = np.arange(0,11)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr[8]

8

In [117]:
arr[1:5]

array([1, 2, 3, 4])

In [118]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [119]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [120]:
# reset
arr = np.arange(0,11)


arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [122]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [123]:
# Now note the changes also occur in our original array!
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [124]:
#To get a copy
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [125]:
# Indexing a 2-D array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [126]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [127]:

# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [128]:
# Getting individual element value
arr_2d[1,0]

20

In [129]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [130]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [131]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [132]:

#Set up matrix
arr2d = np.zeros((10,10))

In [133]:
#Length of array
arr_length = arr2d.shape[1]

In [134]:
arr2d.shape

(10L, 10L)

In [135]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [136]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [137]:
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])